# SPDX-License-Identifier: Apache-2.0
#
# opencode-metrics — build, test, lint, clean, install, backfill, grafana

.DEFAULT_GOAL := help

.PHONY: build test lint check clean install backfill grafana grafana-provision grafana-stop help

##@ Core

build: ## compile the plugin bundle
	bun build src/index.ts --outdir dist --target bun

# Coverage target: 80%. Bun's built-in coverage reports percentages but
# does not enforce thresholds via CLI. Review output manually or add a
# CI script to parse and gate on the 80% minimum.
test: ## run tests with coverage
	bun test --coverage

lint: ## run linters (biome)
	bunx biome check .

check: ## run diagnostic checks (plugin loaded? sessions recording?)
	@bash scripts/check.sh

clean: ## remove build artifacts
	rm -rf dist

##@ Plugin Installation

install: build ## install plugin globally for all OpenCode projects
	@mkdir -p ~/.config/opencode/plugins
	@printf '%s\n' \
		'// SPDX-License-Identifier: Apache-2.0' \
		'// Auto-generated by make install — do not edit.' \
		'// Source: $(CURDIR)' \
		'import plugin from "$(CURDIR)/dist/index.js";' \
		'export const OpenCodeMetrics = plugin;' \
		> ~/.config/opencode/plugins/opencode-metrics.ts
	@echo ""
	@echo "opencode-metrics plugin installed globally."
	@echo "Restart OpenCode to activate."
	@echo ""

##@ Historical Backfill

backfill: ## import historical sessions into the metrics database
	bun run scripts/backfill.ts $(ARGS)

##@ Grafana Dashboard

GRAFANA_DIR        = $(HOME)/.config/opencode/grafana
GRAFANA_REPO_URL   = https://raw.githubusercontent.com/marcusburghardt/ansible-role-ai/main
GRAFANA_PORT       = 3033
GRAFANA_CONTAINER  = opencode-grafana
GRAFANA_VOLUME     = opencode-grafana-data
GRAFANA_DATA_DIR   = $(HOME)/.local/share/opencode-metrics
GRAFANA_IMAGE      = docker.io/grafana/grafana:latest

grafana-provision: ## download provisioning files from ansible-role-ai
	@mkdir -p $(GRAFANA_DIR)/provisioning/datasources
	@mkdir -p $(GRAFANA_DIR)/provisioning/dashboards
	@mkdir -p $(GRAFANA_DIR)/dashboards
	@echo "Downloading provisioning files from ansible-role-ai..."
	@curl -fsSL $(GRAFANA_REPO_URL)/files/grafana/provisioning/datasources/sqlite.yaml \
		-o $(GRAFANA_DIR)/provisioning/datasources/sqlite.yaml
	@curl -fsSL $(GRAFANA_REPO_URL)/files/grafana/provisioning/dashboards/provider.yaml \
		-o $(GRAFANA_DIR)/provisioning/dashboards/provider.yaml
	@curl -fsSL $(GRAFANA_REPO_URL)/files/grafana/dashboards/opencode-metrics.json \
		-o $(GRAFANA_DIR)/dashboards/opencode-metrics.json
	@echo "Provisioning files downloaded to $(GRAFANA_DIR)"

grafana: grafana-provision ## start Grafana container with the metrics dashboard
	@command -v podman >/dev/null 2>&1 || { \
		echo "Error: podman is not installed."; \
		echo "Install: https://podman.io/docs/installation"; \
		exit 1; \
	}
	@test -d "$(GRAFANA_DATA_DIR)" || { \
		echo "Error: Metrics data directory not found: $(GRAFANA_DATA_DIR)"; \
		echo "Run 'make backfill' first, or start an OpenCode session with the plugin."; \
		exit 1; \
	}
	@if podman ps --format '{{.Names}}' 2>/dev/null | grep -q "^$(GRAFANA_CONTAINER)$$"; then \
		echo "Grafana is already running at http://localhost:$(GRAFANA_PORT)"; \
	else \
		podman rm -f $(GRAFANA_CONTAINER) >/dev/null 2>&1 || true; \
		echo "Starting Grafana container..."; \
		podman run -d \
			--name $(GRAFANA_CONTAINER) \
			-p $(GRAFANA_PORT):3000 \
			-v $(GRAFANA_VOLUME):/var/lib/grafana \
			-v $(GRAFANA_DATA_DIR):/data/metrics:ro,Z \
			-v $(GRAFANA_DIR)/provisioning:/etc/grafana/provisioning:ro,Z \
			-v $(GRAFANA_DIR)/dashboards:/var/lib/grafana/dashboards:ro,Z \
			-e GF_INSTALL_PLUGINS=frser-sqlite-datasource \
			-e GF_SECURITY_ADMIN_PASSWORD=admin \
			-e GF_AUTH_ANONYMOUS_ENABLED=true \
			-e GF_AUTH_ANONYMOUS_ORG_ROLE=Admin \
			$(GRAFANA_IMAGE); \
		echo ""; \
		echo "Grafana is starting at http://localhost:$(GRAFANA_PORT)"; \
		echo "First launch may take ~30s while the SQLite plugin installs."; \
		echo "Stop with: make grafana-stop"; \
		echo ""; \
	fi

grafana-stop: ## stop the Grafana container (data volume preserved)
	@podman stop $(GRAFANA_CONTAINER) 2>/dev/null || true
	@podman rm $(GRAFANA_CONTAINER) 2>/dev/null || true
	@echo "Grafana stopped. Data volume '$(GRAFANA_VOLUME)' preserved."

##@ Help

GREEN := \033[0;32m
TEAL := \033[0;36m
CLEAR := \033[0m

help: ## show this help
	@printf "Usage: make $(GREEN)<target>$(CLEAR)\n"
	@awk -v "green=${GREEN}" -v "teal=${TEAL}" -v "clear=${CLEAR}" -F ":.*## *" \
			'/^[a-zA-Z0-9_-]+:/{sub(/:.*/,"",$$1);printf "  %s%-20s%s %s\n", green, $$1, clear, $$2} /^##@/{printf "%s%s%s\n", teal, substr($$1,5), clear}' $(MAKEFILE_LIST)
