// SPDX-License-Identifier: Apache-2.0

import { Database } from "bun:sqlite";
import { chmodSync, existsSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";

/**
 * Schema version for the metrics database.
 * Increment when altering table definitions or adding required migrations.
 */
const SCHEMA_VERSION = 4;

/**
 * V1 metric catalog — seeded into metric_definitions on first database creation.
 * Each entry describes a single observable metric collected per session.
 */
const METRIC_DEFINITIONS: ReadonlyArray<{
	metric_name: string;
	unit: string;
	description: string;
	aggregation: string;
}> = [
	{
		metric_name: "cost",
		unit: "usd",
		description: "Total session cost in USD",
		aggregation: "sum",
	},
	{
		metric_name: "tokens_input",
		unit: "tokens",
		description: "Non-cached input tokens sent to the model",
		aggregation: "sum",
	},
	{
		metric_name: "tokens_output",
		unit: "tokens",
		description: "Output tokens generated by the model",
		aggregation: "sum",
	},
	{
		metric_name: "tokens_reasoning",
		unit: "tokens",
		description: "Reasoning tokens consumed by the model",
		aggregation: "sum",
	},
	{
		metric_name: "tokens_cache_read",
		unit: "tokens",
		description: "Input tokens served from prompt cache",
		aggregation: "sum",
	},
	{
		metric_name: "tokens_cache_write",
		unit: "tokens",
		description: "Input tokens written to prompt cache",
		aggregation: "sum",
	},
	{
		metric_name: "cache_hit_ratio",
		unit: "ratio",
		description: "Fraction of input tokens served from cache",
		aggregation: "avg",
	},
	{
		metric_name: "duration_seconds",
		unit: "seconds",
		description: "Wall-clock session duration in seconds",
		aggregation: "sum",
	},
	{
		metric_name: "files_changed",
		unit: "count",
		description: "Number of files changed in the session",
		aggregation: "sum",
	},
	{
		metric_name: "lines_added",
		unit: "count",
		description: "Lines added across all file changes",
		aggregation: "sum",
	},
	{
		metric_name: "lines_deleted",
		unit: "count",
		description: "Lines deleted across all file changes",
		aggregation: "sum",
	},
	{
		metric_name: "messages_total",
		unit: "count",
		description: "Total messages exchanged in the session",
		aggregation: "sum",
	},
	{
		metric_name: "prs_created",
		unit: "count",
		description: "PRs created in the session",
		aggregation: "sum",
	},
	{
		metric_name: "prs_reviewed",
		unit: "count",
		description: "PRs reviewed in the session",
		aggregation: "sum",
	},
	{
		metric_name: "issues_referenced",
		unit: "count",
		description: "Issues referenced in the session",
		aggregation: "sum",
	},
] as const;

/**
 * Resolve the data directory for opencode-metrics.
 * Uses $XDG_DATA_HOME/opencode-metrics/ when set,
 * falling back to ~/.local/share/opencode-metrics/.
 */
export function getDataDir(): string {
	const xdgDataHome = process.env.XDG_DATA_HOME;
	const base =
		xdgDataHome && xdgDataHome.length > 0 ? xdgDataHome : path.join(homedir(), ".local", "share");
	return path.join(base, "opencode-metrics");
}

/**
 * Create the schema tables for the metrics database.
 * All statements use IF NOT EXISTS for idempotency.
 */
function createSchema(db: Database): void {
	db.run(`
		CREATE TABLE IF NOT EXISTS projects (
			project_id TEXT PRIMARY KEY,
			name       TEXT,
			worktree   TEXT
		)
	`);

	db.run(`
		CREATE TABLE IF NOT EXISTS sessions (
			session_id     TEXT PRIMARY KEY,
			project_id     TEXT,
			agent          TEXT,
			model          TEXT,
			classification TEXT,
			title          TEXT,
			started_at     INTEGER,
			ended_at       INTEGER,
			metadata       TEXT,
			budget_tag     TEXT
		)
	`);

	db.run(`
		CREATE TABLE IF NOT EXISTS metric_definitions (
			metric_name TEXT PRIMARY KEY,
			unit        TEXT,
			description TEXT,
			aggregation TEXT
		)
	`);

	db.run(`
		CREATE TABLE IF NOT EXISTS measurements (
			session_id  TEXT,
			metric_name TEXT,
			value       REAL,
			recorded_at INTEGER,
			PRIMARY KEY (session_id, metric_name)
		)
	`);

	db.run(
		"CREATE INDEX IF NOT EXISTS idx_measurements_time ON measurements (recorded_at, metric_name)",
	);
	db.run(
		"CREATE INDEX IF NOT EXISTS idx_measurements_metric ON measurements (metric_name, recorded_at)",
	);

	// Convenience views exposing timestamps as epoch seconds and ISO-8601
	// strings. Base tables store epoch milliseconds (SDK passthrough);
	// these views eliminate the /1000 conversion gymnastics for Grafana
	// and other downstream consumers.
	db.run(`
		CREATE VIEW IF NOT EXISTS v_sessions AS
		SELECT
			session_id, project_id, agent, model, classification, title,
			started_at / 1000 AS started_at_epoch,
			ended_at / 1000 AS ended_at_epoch,
			strftime('%Y-%m-%dT%H:%M:%SZ', started_at / 1000, 'unixepoch') AS started_at_iso,
			strftime('%Y-%m-%dT%H:%M:%SZ', ended_at / 1000, 'unixepoch') AS ended_at_iso,
			metadata,
			budget_tag
		FROM sessions
	`);

	db.run(`
		CREATE VIEW IF NOT EXISTS v_measurements AS
		SELECT
			session_id, metric_name, value,
			recorded_at / 1000 AS recorded_at_epoch,
			strftime('%Y-%m-%dT%H:%M:%SZ', recorded_at / 1000, 'unixepoch') AS recorded_at_iso
		FROM measurements
	`);

	// Session artifacts table — records specific PRs and issues a session
	// interacted with. PK deduplication ensures the same PR referenced
	// multiple times (view + diff + checks) produces one row, not three.
	db.run(`
		CREATE TABLE IF NOT EXISTS session_artifacts (
			session_id    TEXT,
			artifact_type TEXT,
			reference     TEXT,
			recorded_at   INTEGER,
			PRIMARY KEY (session_id, artifact_type, reference)
		)
	`);

	// Secondary index for cross-session artifact queries (e.g., "all
	// sessions that touched PR org/repo#123").
	db.run(
		"CREATE INDEX IF NOT EXISTS idx_artifacts_reference ON session_artifacts (reference, artifact_type)",
	);

	// Convenience view — same pattern as v_measurements: expose
	// recorded_at as epoch seconds and ISO-8601 string.
	db.run(`
		CREATE VIEW IF NOT EXISTS v_session_artifacts AS
		SELECT
			session_id, artifact_type, reference,
			recorded_at / 1000 AS recorded_at_epoch,
			strftime('%Y-%m-%dT%H:%M:%SZ', recorded_at / 1000, 'unixepoch') AS recorded_at_iso
		FROM session_artifacts
	`);

	// Task 1.1: measurement_deltas table — stores incremental changes per
	// metric on each idle event, enabling accurate time-sliced aggregation
	// (e.g., daily cost) even for multi-day sessions.
	db.run(`
		CREATE TABLE IF NOT EXISTS measurement_deltas (
			session_id  TEXT,
			metric_name TEXT,
			delta       REAL,
			recorded_at INTEGER,
			PRIMARY KEY (session_id, metric_name, recorded_at)
		)
	`);

	// Task 1.2: Secondary index for efficient cross-session aggregation
	// queries that filter by metric name and aggregate across time ranges.
	db.run(
		"CREATE INDEX IF NOT EXISTS idx_deltas_metric_time ON measurement_deltas (metric_name, recorded_at)",
	);

	// Task 1.3: Convenience view — same pattern as v_measurements:
	// expose recorded_at as epoch seconds and ISO-8601 string.
	db.run(`
		CREATE VIEW IF NOT EXISTS v_measurement_deltas AS
		SELECT
			session_id, metric_name, delta,
			recorded_at / 1000 AS recorded_at_epoch,
			strftime('%Y-%m-%dT%H:%M:%SZ', recorded_at / 1000, 'unixepoch') AS recorded_at_iso
		FROM measurement_deltas
	`);

	// Task 2.1: Cost pricing table — stores user-supplied per-token prices
	// for model patterns. Prices are in USD per million tokens. The
	// priority column reflects config array order (0 = highest priority)
	// for first-match-wins semantics in the adjusted cost views.
	db.run(`
		CREATE TABLE IF NOT EXISTS cost_pricing (
			model_pattern    TEXT PRIMARY KEY,
			priority         INTEGER NOT NULL,
			input_price      REAL NOT NULL,
			output_price     REAL NOT NULL,
			cache_read_price REAL,
			cache_write_price REAL,
			reasoning_price  REAL,
			description      TEXT,
			updated_at       INTEGER
		)
	`);

	// Task 2.2: Adjusted costs view — computes per-session adjusted cost
	// using user-supplied pricing rules matched via LIKE patterns.
	// Design decisions (see design.md D4, D5, D6):
	// - CTE-based pivoting: single pass over measurements EAV table
	// - First-match-wins: ROW_NUMBER() OVER (PARTITION BY ... ORDER BY priority)
	// - Reasoning price fallback: COALESCE(reasoning_price, output_price)
	// - No pricing match fallback: original cost passthrough via COALESCE
	db.run(`
		CREATE VIEW IF NOT EXISTS v_adjusted_costs AS
		WITH session_metrics AS (
			SELECT
				session_id,
				SUM(CASE WHEN metric_name = 'cost' THEN value END) AS cost,
				SUM(CASE WHEN metric_name = 'tokens_input' THEN value END) AS tokens_input,
				SUM(CASE WHEN metric_name = 'tokens_output' THEN value END) AS tokens_output,
				SUM(CASE WHEN metric_name = 'tokens_reasoning' THEN value END) AS tokens_reasoning,
				SUM(CASE WHEN metric_name = 'tokens_cache_read' THEN value END) AS tokens_cache_read,
				SUM(CASE WHEN metric_name = 'tokens_cache_write' THEN value END) AS tokens_cache_write,
				MAX(recorded_at) AS recorded_at
			FROM measurements
			GROUP BY session_id
		),
		matched_pricing AS (
			SELECT
				sm.session_id,
				cp.input_price,
				cp.output_price,
				cp.cache_read_price,
				cp.cache_write_price,
				cp.reasoning_price,
				ROW_NUMBER() OVER (
					PARTITION BY sm.session_id
					ORDER BY cp.priority
				) AS rn
			FROM session_metrics sm
			JOIN sessions s ON s.session_id = sm.session_id
			JOIN cost_pricing cp ON s.model LIKE cp.model_pattern
		)
		SELECT
			s.session_id,
			s.model,
			s.classification,
			s.budget_tag,
			s.project_id,
			sm.cost AS original_cost,
			COALESCE(
				(COALESCE(sm.tokens_input, 0) * mp.input_price / 1000000.0) +
				(COALESCE(sm.tokens_output, 0) * mp.output_price / 1000000.0) +
				(COALESCE(sm.tokens_cache_read, 0) * COALESCE(mp.cache_read_price, 0) / 1000000.0) +
				(COALESCE(sm.tokens_cache_write, 0) * COALESCE(mp.cache_write_price, 0) / 1000000.0) +
				(COALESCE(sm.tokens_reasoning, 0) * COALESCE(mp.reasoning_price, mp.output_price) / 1000000.0),
				sm.cost
			) AS adjusted_cost,
			COALESCE(
				(COALESCE(sm.tokens_input, 0) * mp.input_price / 1000000.0) +
				(COALESCE(sm.tokens_output, 0) * mp.output_price / 1000000.0) +
				(COALESCE(sm.tokens_cache_read, 0) * COALESCE(mp.cache_read_price, 0) / 1000000.0) +
				(COALESCE(sm.tokens_cache_write, 0) * COALESCE(mp.cache_write_price, 0) / 1000000.0) +
				(COALESCE(sm.tokens_reasoning, 0) * COALESCE(mp.reasoning_price, mp.output_price) / 1000000.0),
				sm.cost
			) - sm.cost AS cost_difference,
			sm.recorded_at / 1000 AS recorded_at_epoch,
			strftime('%Y-%m-%dT%H:%M:%SZ', sm.recorded_at / 1000, 'unixepoch') AS recorded_at_iso
		FROM session_metrics sm
		JOIN sessions s ON s.session_id = sm.session_id
		LEFT JOIN matched_pricing mp ON mp.session_id = sm.session_id AND mp.rn = 1
	`);

	// Task 2.3: Adjusted cost deltas view — same CTE pattern as
	// v_adjusted_costs but reading from measurement_deltas. Enables
	// accurate time-sliced adjusted cost aggregation for Grafana.
	db.run(`
		CREATE VIEW IF NOT EXISTS v_adjusted_cost_deltas AS
		WITH delta_metrics AS (
			SELECT
				session_id,
				SUM(CASE WHEN metric_name = 'cost' THEN delta END) AS cost_delta,
				SUM(CASE WHEN metric_name = 'tokens_input' THEN delta END) AS tokens_input,
				SUM(CASE WHEN metric_name = 'tokens_output' THEN delta END) AS tokens_output,
				SUM(CASE WHEN metric_name = 'tokens_reasoning' THEN delta END) AS tokens_reasoning,
				SUM(CASE WHEN metric_name = 'tokens_cache_read' THEN delta END) AS tokens_cache_read,
				SUM(CASE WHEN metric_name = 'tokens_cache_write' THEN delta END) AS tokens_cache_write,
				recorded_at
			FROM measurement_deltas
			GROUP BY session_id, recorded_at
		),
		matched_pricing AS (
			SELECT
				dm.session_id,
				dm.recorded_at,
				cp.input_price,
				cp.output_price,
				cp.cache_read_price,
				cp.cache_write_price,
				cp.reasoning_price,
				ROW_NUMBER() OVER (
					PARTITION BY dm.session_id, dm.recorded_at
					ORDER BY cp.priority
				) AS rn
			FROM delta_metrics dm
			JOIN sessions s ON s.session_id = dm.session_id
			JOIN cost_pricing cp ON s.model LIKE cp.model_pattern
		)
		SELECT
			s.session_id,
			s.model,
			s.classification,
			s.budget_tag,
			s.project_id,
			dm.cost_delta AS original_cost_delta,
			COALESCE(
				(COALESCE(dm.tokens_input, 0) * mp.input_price / 1000000.0) +
				(COALESCE(dm.tokens_output, 0) * mp.output_price / 1000000.0) +
				(COALESCE(dm.tokens_cache_read, 0) * COALESCE(mp.cache_read_price, 0) / 1000000.0) +
				(COALESCE(dm.tokens_cache_write, 0) * COALESCE(mp.cache_write_price, 0) / 1000000.0) +
				(COALESCE(dm.tokens_reasoning, 0) * COALESCE(mp.reasoning_price, mp.output_price) / 1000000.0),
				dm.cost_delta
			) AS adjusted_cost_delta,
			COALESCE(
				(COALESCE(dm.tokens_input, 0) * mp.input_price / 1000000.0) +
				(COALESCE(dm.tokens_output, 0) * mp.output_price / 1000000.0) +
				(COALESCE(dm.tokens_cache_read, 0) * COALESCE(mp.cache_read_price, 0) / 1000000.0) +
				(COALESCE(dm.tokens_cache_write, 0) * COALESCE(mp.cache_write_price, 0) / 1000000.0) +
				(COALESCE(dm.tokens_reasoning, 0) * COALESCE(mp.reasoning_price, mp.output_price) / 1000000.0),
				dm.cost_delta
			) - dm.cost_delta AS cost_delta_difference,
			dm.recorded_at / 1000 AS recorded_at_epoch,
			strftime('%Y-%m-%dT%H:%M:%SZ', dm.recorded_at / 1000, 'unixepoch') AS recorded_at_iso
		FROM delta_metrics dm
		JOIN sessions s ON s.session_id = dm.session_id
		LEFT JOIN matched_pricing mp ON mp.session_id = dm.session_id AND mp.recorded_at = dm.recorded_at AND mp.rn = 1
	`);
}

/**
 * Seed the metric_definitions table with the V1 metric catalog.
 * Uses INSERT OR IGNORE so existing rows are never overwritten,
 * making this safe to call on every startup.
 */
export function ensureMetricDefinitions(db: Database): void {
	const stmt = db.prepare(
		"INSERT OR IGNORE INTO metric_definitions (metric_name, unit, description, aggregation) VALUES (?, ?, ?, ?)",
	);

	for (const metric of METRIC_DEFINITIONS) {
		stmt.run(metric.metric_name, metric.unit, metric.description, metric.aggregation);
	}
}

/**
 * Result returned by initDatabase(), giving the caller both the
 * opened Database handle and the resolved data directory path.
 */
export interface InitDatabaseResult {
	db: Database;
	dataDir: string;
}

/**
 * Initialize the metrics database.
 *
 * 1. Resolves the data directory (XDG_DATA_HOME or fallback).
 * 2. Creates the directory with 0o755 if it doesn't exist.
 * 3. Opens (or creates) metrics.db with WAL mode and busy_timeout.
 * 4. Creates all schema tables idempotently.
 * 5. Sets PRAGMA user_version on first creation.
 * 6. Seeds the metric_definitions catalog.
 *
 * @param dataDirOverride — optional path override for testing.
 */
export function initDatabase(dataDirOverride?: string): InitDatabaseResult {
	const dataDir = dataDirOverride ?? getDataDir();

	if (!existsSync(dataDir)) {
		mkdirSync(dataDir, { recursive: true, mode: 0o755 });
	}

	const dbPath = path.join(dataDir, "metrics.db");
	const isNewDb = !existsSync(dbPath);
	const db = new Database(dbPath, { create: true });

	// Ensure restrictive permissions on the database file (0o644).
	if (isNewDb) {
		chmodSync(dbPath, 0o644);
	}

	// WAL mode for concurrent read access and busy_timeout for contention.
	db.run("PRAGMA journal_mode = WAL");
	db.run("PRAGMA busy_timeout = 5000");

	createSchema(db);

	// Schema versioning: set user_version when the database schema is
	// behind the current version. CREATE TABLE/INDEX/VIEW IF NOT EXISTS
	// makes the migration idempotent — the version bump reflects the
	// actual schema state after createSchema() runs.
	const versionRow = db.prepare("PRAGMA user_version").get() as { user_version: number } | null;
	const currentVersion = versionRow?.user_version ?? 0;

	// V2 → V3 migration: add budget_tag column to sessions table.
	// Guard with try/catch because ALTER TABLE ADD COLUMN fails if the
	// column already exists (e.g., fresh v3 database created by
	// createSchema above). SQLite does not support IF NOT EXISTS for
	// ALTER TABLE ADD COLUMN.
	if (currentVersion < 3) {
		try {
			db.run("ALTER TABLE sessions ADD COLUMN budget_tag TEXT");
		} catch (_error: unknown) {
			// Column already exists — safe to ignore (fresh v3 database
			// or migration already applied).
		}
	}

	// V3 → V4 migration: add cost_pricing table and adjusted cost views.
	// No ALTER TABLE needed — the new table and views are created by
	// createSchema() above with IF NOT EXISTS. The version bump below
	// reflects the actual schema state after createSchema() runs.
	// (Guard is implicit: currentVersion < 4 falls through to the
	// generic version bump below.)

	if (currentVersion < SCHEMA_VERSION) {
		db.run(`PRAGMA user_version = ${SCHEMA_VERSION}`);
	}

	ensureMetricDefinitions(db);

	return { db, dataDir };
}
